/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        border: "var(--border)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        input: "var(--input)",
        ring: "var(--ring)",
        outline: "#777777",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "tertiary-fixed": "#5e5e5e",
        "error-container": "#ffdad6",
        "surface-container": "#eeeeee",
        "on-primary": "#e2e2e2",
        "primary-fixed": "#5e5e5e",
        "primary-fixed-dim": "#474747",
        "tertiary-container": "#747474",
        "surface-dim": "#dadada",
        "surface-container-low": "#f3f3f4",
        "tertiary-fixed-dim": "#474747",
        "secondary-container": "#d6d4d3",
        "outline-variant": "#c6c6c6",
        "on-primary-fixed-variant": "#e2e2e2",
        "on-error-container": "#410002",
        "on-surface-variant": "#474747",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-fixed": "#ffffff",
        tertiary: "#3b3b3b",
        "surface-container-high": "#e8e8e8",
        "inverse-primary": "#c6c6c6",
        "surface-bright": "#f9f9f9",
        "on-tertiary-container": "#ffffff",
        "secondary-fixed": "#c8c6c6",
        "secondary-fixed-dim": "#acabab",
        "on-primary-container": "#ffffff",
        "surface-tint": "#5e5e5e",
        "on-tertiary": "#e2e2e2",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#2f3131",
        "surface-variant": "#e2e2e2",
        "on-primary-fixed": "#ffffff",
        "primary-container": "#3b3b3b",
        error: "#ba1a1a",
        "inverse-on-surface": "#f0f1f1",
        "on-secondary-fixed": "#1b1c1c",
        "on-surface": "#1a1c1c",
        "on-secondary-container": "#1b1c1c",
        "on-secondary-fixed-variant": "#3b3b3b",
        "surface-container-lowest": "#ffffff",
        surface: "#f9f9f9",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        serif: ["var(--font-newsreader)", "serif"],
        headline: ["var(--font-newsreader)", "serif"],
        body: ["var(--font-sans)", "sans-serif"],
        label: ["var(--font-sans)", "sans-serif"],
      },
    },
  },
  plugins: [],
}
